version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-aats}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-aats_pass}
      POSTGRES_DB: ${POSTGRES_DB:-aats_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

  backend:
    build: ./be
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER:-aats}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-aats_pass}
      - DB_NAME=${POSTGRES_DB:-aats_db}
      - JWT_SECRET=${JWT_SECRET:-secret}
    ports:
      - "8080:8080"

volumes:
  pgdata:
